alias bi="brew info"
alias bci="brew info --cask"
alias bs="brew search"
alias bcs="brew search --cask"
alias bii="brew install"
alias bcii="brew install --cask"
alias buv="brew update -v"
alias blf="brew list --full-name"
alias bclf="brew list --cask --full-name"
alias blff="brew list --formula --full-name"
alias bog="brew outdated --greedy"
alias bcog="brew outdated --cask --greedy"
alias bug="brew upgrade --greedy"
alias bcug="brew upgrade --cask --greedy"

# export HOMEBREW_NO_ANALYTICS="1"
export HOMEBREW_AUTO_UPDATE_SECS="86400"
