[project]
name = "dotf"
version = "0.1.0"
description = '''Dotfiles cli
#
#      _       _    __
#   __| | ___ | |_ / _|
#  / _` |/ _ \| __| |_
# | (_| | (_) | |_|  _|
#  \__,_|\___/ \__|_|
#
'''

[project.meta]
author = "lazyboy <lazyboy.fan@gmail.com>"
# dotenv = ".env.local"
require-tools = [
    "sed",
    "awk",
    "git",
    "shfmt",
    "icli",
]
# man-section = 1
inherit-flag-options = true
# combine-shorts = true
# symbol = "+toolchain[`_choice_fn`]"

# [cli]
# name = "dotf"
