# Global
DOTF_ROOT="${DOTFILES_ROOT:-${HOME}/.dotfiles}"
DOTF_PKG_DIR="${DOTF_ROOT}/packages"
DOTF_LAYOUT_DIR="${DOTF_PKG_DIR}/os/layouts"

# Link
DOTF_LINK_STOW_SRC="${DOTF_PKG_DIR}"
DOTF_LINK_STOW_TARGET="${HOME}"
DOTF_LINK_EXCLUDE_PACKAGES=(.git .venv .vscode)
DOTF_LINK_EXCLUDE_PACKAGES_STRING=$(
    IFS=:
    echo "${DOTF_LINK_EXCLUDE_PACKAGES[*]}"
)
